### PR TITLE
Simplify example of stdio_set_chars_available_callback

### LINKED ISSUE #461: Make sure there's an example of using stdio_set_chars_available_callback
Make sure it works with USB
See https://github.com/raspberrypi/pico-sdk/issues/1603

### PR DESCRIPTION
**Pull request by peterharperuk**
The example in here uses an async callback to avoid a race when using stdio_usb. But there's a fix available for this issue so simplify the example.

To test pass -DPICO_STDIO_USB=1 on the cmake command line.

Fixes #461

### CODE REVIEW

**Comment by peterharperuk** [comment]
Requires this fix in the sdk https://github.com/raspberrypi/pico-sdk/pull/1649

**Comment by peterharperuk** [comment]
@kilograham Simple fix to remove some of my sillyness. Will merge if that's ok.

**Review by kilograham — APPROVED** [review]
prepared to believe you ;-) though curious what / why of the disable_sta_mode?

**Comment by peterharperuk** [comment]
This is "demonstrating" clean shutdown of the wifi stack. The loop keeps going while the link is up so pressing "d" calls disable_sta_mode which disables wifi and causes the program to exit.

**Pull request merged**
