### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by JamesH65**
Fix up the List of files section.

### CODE REVIEW

**Comment by JamesH65** [comment]
@lurch @kilograham

**Review by lurch — APPROVED** [review]
LGTM

**Comment by JamesH65** [comment]
If you review and accept, I can merge.

**Comment by lurch** [comment]
I don't have write-perms on this repo, my approval above is the best I can do :slightly_smiling_face:

**Comment by JamesH65** [comment]
Hmm, I thought it just needed you to officially approve, then I could merge.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
