### PR TITLE
bus_scan.c example - fix pin number in comment

### PR DESCRIPTION
**Pull request by a-h**
The comment in the code is incorrect. I tested this out, and it doesn't detect the device via those pins.

I was searching and found this comment thread: https://www.raspberrypi.org/forums/viewtopic.php?p=1822258&sid=1ff96911779abcedda7b3ae535d1d0af#p1822258

Sure enough, when I switched to pins 6 and 7, the code worked fine and could detect the device I had plugged into the i2c bus.

```
I2C Bus Scan
   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
00 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
10 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
20 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
30 .  .  .  .  .  .  .  .  .  .  .  .  @  .  .  .
40 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
50 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
60 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
70 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
Done.
```

Example wiring.

pico

### CODE REVIEW

**Comment by lurch** [comment]
The comment is correct, it's referring to the GPIO numbers, and the "default I2C pins" are defined in https://github.com/raspberrypi/pico-sdk/blob/master/src/boards/include/boards/pico.h

You seem to be confusing "GPIO numbers" with "physical pins" - see the diagram at https://www.raspberrypi.org/documentation/rp2040/getting-started/#board-specifications
So if you wanted to submit an alternative PR where you change "(4, 5 on a Pico)" to "(GP4, GP5 on a Pico)" I think we might be willing to accept that. ping @aallan ?

**Comment by a-h** [comment]
Great. As you can see, I wasn't the first person to be confused by that, and wouldn't be the last.

Prefixing GPIO numbers with GP would remove any ambiguity about what the number means and it matches the pinout diagram (https://datasheets.raspberrypi.org/pico/Pico-R3-A4-Pinout.pdf).

**Comment by a-h** [comment]
I've updated based on your suggestion.

**Review by lurch — DISMISSED** [review]

**Comment by JamesH65** [comment]
@lurch Can you approve this so that Github actually thinks its approved? Or don't you have write access? @kilograham?

**Review by aallan — DISMISSED** [review]

**Comment by aallan** [comment]
Done @JamesH65

**Comment by JamesH65** [comment]
Feel free to merge

**Comment by lurch** [comment]
> @lurch Can you approve this so that Github actually thinks its approved? Or don't you have write access?

IIRC the only Pico-related repo I have write access to is `pico-feedback`.

**Pull request merged**
