### PR TITLE
fix pio/onewire_library CMakeLists.txt

### PR DESCRIPTION
**Pull request by mjcross**
Add missing INTERFACE keyword and path to `target_sources()` in pio/onewire/onewire_library/CMakeLists.txt.
Add the `onewire` subdirectory to pio/CMakeLists.

### CODE REVIEW

**Comment by peterharperuk** [comment]
Looks good to me

**Review by peterharperuk — DISMISSED** [review]

**Comment by mjcross** [comment]
Apologies - I pushed a **new** example (pio/7_segment) to this existing fork by mistake.

**Comment by lurch** [comment]
@mjcross I guess you'll want to create a new branch with just this fix on, and then create a new PR from that?

**Comment by mjcross** [comment]
Sure Andrew - I can do that, but @peterharperuk had already approved the PR for the onewire fix on 25 Apr so I wasn’t sure if I’d inadvertently screwed things up by closing the PR.

Happy to create a new PR again if that’s preferred ?

**Comment by mjcross** [comment]
@lurch sounds like the best thing might be for me to close both this PR and the one for the new 7-Segment example, then create two new ones. My fault: I'm not really familiar enough with **git** to realise that I should have put them on separate branches!

**Comment by lurch** [comment]
No worries, `git` is a big learning curve for everybody at first :slightly_smiling_face:

**Pull request closed without merging**
