### PR TITLE
Fix freertos compilation

### PR DESCRIPTION
**Pull request by peterharperuk**
Issues with the latest version of the FreeRTOS-Kernel

### CODE REVIEW

**Comment by ex-fil** [comment]
This worked for me :top:

**Comment by lurch** [comment]
I guess this conflicts with #460 ?

**Comment by lurch** [comment]
I guess this also relates to https://github.com/raspberrypi/pico-sdk/pull/1530 ?

**Comment by peterharperuk** [comment]
@kilograham I know we need to see if freertos have broken something else, but are you ok with me merging this? As it's better than nothing?

**Pull request merged**
