### PR TITLE
change blink to use PICO_DEFAULT_LED_PIN to support other boards

### PR DESCRIPTION
**Pull request by hathach**
This help the example to run with upcoming board without code modification from user.

### CODE REVIEW

**Comment by lurch** [comment]
There's also similar in:
https://github.com/raspberrypi/pico-examples/blob/master/picoboard/blinky/blinky.c
https://github.com/raspberrypi/pico-examples/blob/master/pio/pwm/pwm.c

**Comment by Wren6991** [comment]
Note the `hello_double_tap` change will conflict with #53 -- could you remove that one from this PR please?

**Comment by lurch** [comment]
#53 has now been merged, so (hopefully) all you need to do is rebase against the latest `develop` branch.

**Comment by hathach** [comment]
I have rebased and push-force

**Review by Wren6991 — APPROVED** [review]

**Pull request merged**
