### PR TITLE
Update comment to match code output

### PR DESCRIPTION
**Pull request by nathan-contino**
* closes https://github.com/raspberrypi/pico-feedback/issues/34

### CODE REVIEW

**Comment by nathan-contino** [comment]
Tagging @aallan to help get this merged.

**Comment by aallan** [comment]
> Tagging @aallan to help get this merged.

🎪🙈🙉🙊

**Review by peterharperuk — APPROVED** [review]

**Review by peterharperuk — CHANGES_REQUESTED** [review]
Can you please change the branch to "develop"

**Comment by nathan-contino** [comment]
Updated, @peterharperuk !

**Review by peterharperuk — APPROVED** [review]

**Pull request merged**
