### PR TITLE
Added a 14 segment LED example, driven by the HT16K33

### PR DESCRIPTION
**Pull request by JamesH65**
No fritzing parts available for the device so no diagrams

### CODE REVIEW

**Comment by JamesH65** [comment]
This still needs merging. Works fine, no conflicts.

**Comment by JamesH65** [comment]
Closing as against wrong branch (master instead of develop)

**Comment by JamesH65** [comment]
Reopening - how on earth do I change the destination branch?

**Comment by JamesH65** [comment]
Ah, figured it out. Ready to merge.

**Comment by JamesH65** [comment]
@kilograham Since you are on a PR clean out, is this one OK?

**Review by kilograham — APPROVED** [review]

**Comment by JamesH65** [comment]
Thanks!

**Pull request merged**
