### PR TITLE
Add Python test scripts and rename MicroPython scripts

### PR DESCRIPTION
**Pull request by mucahitkurtlar**
In Pico W TCP example test script was written in MicroPython. I needed to test on my desktop so I wrote tests in Python (not MicroPython) and think other people may need these test scripts.

### CODE REVIEW

**Comment by lurch** [comment]
Because of the simultaneous rename-and-add, it can be a bit tricky to see exactly what this PR is doing, so just to help make things clearer:
* `pico_w/python_test_tcp/python_test_tcp_client.py` has been renamed to `pico_w/python_test_tcp/micropython_test_tcp_client.py` (without any extra edits)
* `pico_w/python_test_tcp/python_test_tcp_server.py` has been renamed to `pico_w/python_test_tcp/micropython_test_tcp_server.py` (without any extra edits)
* A new `pico_w/python_test_tcp/python_test_tcp_client.py` script has been added (which uses "regular Python" rather than MicroPython)
* A new `pico_w/python_test_tcp/python_test_tcp_server.py` script has been added (which uses "regular Python" rather than MicroPython)

@peterharperuk @kilograham @aallan I wonder if it _might_ make sense to move the `micropython_*.py` scripts into the https://github.com/raspberrypi/pico-micropython-examples repo?

**Comment by peterharperuk** [comment]
yeah - we could move the micropython versions. We just need something to take the place of the other end of the C code examples. It was remiss of me to make micropython only versions. Bonus points if you can make a version that is OS agnostic.

**Comment by peterharperuk** [comment]
Bit confused why there are 3 commits in here. It looks like they need squashing into one before they can be merged?

**Comment by kilograham** [comment]
> Bit confused why there are 3 commits in here. It looks like they need squashing into one before they can be merged?

number of commits doesn't matter, I will squash when i merge

**Comment by mucahitkurtlar** [comment]
So... Why are we still waiting? (:

**Review by peterharperuk — APPROVED** [review]
All looks good to me.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
