### PR TITLE
Updated deprecated cortex-debug debug attributes

### PR DESCRIPTION
**Pull request by jamd315**
Attempts to fix issue #262, section 7.3 in the getting started PDF may also need to be updated but I wasn't sure how to do that.

### CODE REVIEW

**Comment by lurch** [comment]
> section 7.3 in the getting started PDF may also need to be updated but I wasn't sure how to do that.

Probably best to file an issue at https://github.com/raspberrypi/pico-feedback

**Comment by P33M** [comment]
LGTM - this matches what we have been testing internally

**Review by andygpz11 — COMMENTED** [review]
This looks good to me, thanks.
I think the changes here are a sub-set of those I just tested and approved in #313
So, I'm not sure we need this if we merge #313 (but I'm happy).

**Comment by kilograham** [comment]
closed in favor of #313

**Pull request closed without merging**
