### PR TITLE
added comments for clarification

### PR DESCRIPTION
**Pull request by SEEK-THE-VOID-LIGHT**
I added comments to the blink.c script for beginners to get a better overview of the example script.
When I began with embedded system I would have liked that in my showcase examples, so I wanted to add that to the Raspberry Pi Pico example script.
The code without comments can be a bit intimidating for new users.

### CODE REVIEW

**Comment by aallan** [comment]
The example code gets pulled in automagically into the PDF documentation. We can't really have heavy inline commenting for that reason.

**Comment by SEEK-THE-VOID-LIGHT** [comment]
Ok, should I shorten the comments?

**Comment by aallan** [comment]
I'd would tend to agree, I think the code looks awfully cluttered with that amount of additional commentary. A README.md file might be a more appropriate place.

**Comment by SEEK-THE-VOID-LIGHT** [comment]
Should I wait for further rsponse, make a readme, or close the request?

**Comment by lurch** [comment]
If I was you I'd revert the changes you've made to `blink.c`, create a `README.md` instead, and then wait to see what @kilograham says...

**Comment by SEEK-THE-VOID-LIGHT** [comment]
👍

**Comment by SEEK-THE-VOID-LIGHT** [comment]
The README now holds the commented version of the code, I can change the content if you want.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
