### PR TITLE
Update gitignore to ignore CMake generated files

### PR DESCRIPTION
**Pull request by protik09**

### CODE REVIEW

**Comment by lurch** [comment]
Don't these normally end up being created inside the `build` folder anyway?

**Comment by protik09** [comment]
I had them cluttering up the repo outside build, so just dropped in my CMake gitignore to fix it.

**Comment by peterharperuk** [comment]
@lurch  is correct. It looks like you have run cmake in the source folder. It's usual to do this...

cd pico-examples
mkdir build
cd build
cmake ..
make -j8

We already ignore the build folder.

**Comment by lurch** [comment]
@protik09 See also https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf

**Comment by peterharperuk** [comment]
Closing this as it's not required

**Pull request closed without merging**
