### PR TITLE
Update README.adoc's for various examples to remove unnecessary block callouts.

### PR DESCRIPTION
**Pull request by JamesH65**
Various fixes for odd formatting in the example README's

### CODE REVIEW

**Review by aallan — APPROVED** [review]
Can you merge @kilograham?

**Comment by aallan** [comment]
Thanks!

**Comment by lurch** [comment]
@kilograham Could you also cherry-pick / merge these changes onto the `develop` branch of pico-examples please?

**Comment by lurch** [comment]
Great, ta!

**Pull request merged**
